package igu;

import fravemax.AccesoADatos.ProductoXProveedorData;
import fravemax.AccesoADatos.ProveedorData;
import fravemax.Entidades.ProductoXProveedor;
import fravemax.Entidades.Proveedor;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAEL
 */
public class ReporteProductoProveedorView extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    ProveedorData proveedorData;
    ProductoXProveedorData pXProveedor;
    ArrayList<Proveedor> proveedores;

    /**
     * Creates new form ReporteProductoView
     */
    public ReporteProductoProveedorView() {
        initComponents();
        modelo = new DefaultTableModel();
        proveedorData = new ProveedorData();
        pXProveedor = new ProductoXProveedorData();
        proveedores = (ArrayList) proveedorData.listarProveedores();
        armarLista();
        armarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/img/FraveMax.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProveedor = new javax.swing.JTable();
        jcProveedor = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte de Productos");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setDoubleBuffered(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTADO DE PRODUCTOS POR PROVEEDOR");

        jtProveedor.setBackground(new java.awt.Color(204, 204, 255));
        jtProveedor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtProveedor.setForeground(new java.awt.Color(0, 0, 255));
        jtProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Descripcion", "stock"
            }
        ));
        jtProveedor.setToolTipText("");
        jtProveedor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jtProveedor);
        if (jtProveedor.getColumnModel().getColumnCount() > 0) {
            jtProveedor.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtProveedor.getColumnModel().getColumn(1).setPreferredWidth(360);
            jtProveedor.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jcProveedor.setBackground(new java.awt.Color(204, 204, 255));
        jcProveedor.setForeground(new java.awt.Color(0, 0, 255));
        jcProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jcProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jcProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcProveedorActionPerformed
        // TODO add your handling code here:
        borrarTabla();
        llenarTabla();
    }//GEN-LAST:event_jcProveedorActionPerformed

    private void borrarTabla() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Proveedor> jcProveedor;
    private javax.swing.JTable jtProveedor;
    // End of variables declaration//GEN-END:variables

    private void armarLista() {
        for (Proveedor aux : proveedores) {
            jcProveedor.addItem(aux);
        }
    }

    private void armarTabla() {
        ArrayList<Object> column = new ArrayList();
        column.add("Id");
        column.add("Descripcion");
        column.add("Precio");
        for (Object object : column) {
            modelo.addColumn(object);
        }
        jtProveedor.setModel(modelo);
        jtProveedor.getColumnModel().getColumn(0).setPreferredWidth(30);
        jtProveedor.getColumnModel().getColumn(1).setPreferredWidth(360);
        jtProveedor.getColumnModel().getColumn(2).setPreferredWidth(100);
    }

    private void llenarTabla() {
        Proveedor pro = (Proveedor) jcProveedor.getSelectedItem();
        int seleccionado = pro.getIdProveedor();
        ArrayList<ProductoXProveedor> producto = (ArrayList<ProductoXProveedor>) pXProveedor.listarDetalleXProveedor1(seleccionado);
        for (ProductoXProveedor aux : producto) {
            modelo.addRow(new Object[]{aux.getIdProducto().getIdProducto(), aux.getIdProducto().getDescripcion(), aux.getPrecioCosto()});

        }

    }

}
